services:

  mongo:
    image: mongo:7.0.17
    restart: always
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGO
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - MONGO
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"

  # As the Marktstammdatenregister (Mastr) is an external service, WireMock is used for testing.
  # WireMock is an open-source tool for API mock testing.
  # The tests are realized with Cucumber, a test framework for Behavior-Driven Development,
  # which are stored in the test folder. The mocks are configured there.
  mastr-wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8082:8080"

  # Also Opendatasoft is an external service that is mocked for testing.
  opendatasoft-wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8083:8080"

  # Mailing by contact form or the campaign "Now we need roofs" can be tested with MailHog.
  # See application.properties in main for configuration.
  # website: http://localhost:8080/
  # mailhog: http://localhost:8025/
  mailserver-dev:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025" # smtp
      - "8025:8025" # http

networks:
  MONGO:
    name: MONGO
